### ISSUE TITLE
DELETED SHIP in IOS wows info pro

### ISSUE THREAD

**Issue by flying0420** [HenryQuan/WoWs-Info#8]
Hi,

I just downloaded app wows info pro in IOS. In war ship tab, all ships show as DELETED SHIP. Please be noted of this errror. Looking forward to your update, it helps a lot!

**Comment by HenryQuan** [comment]
Hello,
Thank you reporting this issue and I have just fixed it earlier. I am planning for an update soon.
This issue is caued by react native device info. They seemed to update it and the old require style failed.
Once again thank you for your support.

**Comment by HenryQuan** [comment]
The update is now alive. Please update and see if it works.
I will close this issue for now. Feel free to open it again.

**Comment by flying0420** [comment]
It's working prefect. thx!
